<?php

use App\Models\PortfolioItem;
use App\Models\PortfolioItemTag;
use App\Models\PortfolioItemTechTag;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PortfolioItemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $seedFakeItems = false;
        $seedRealItems = true;

        // Clear the Portfolio items table
        PortfolioItem::truncate();

        // Clear the portfio items tag pivot table
        DB::table('portfolio_item_tag_pivot')->truncate();

        // Clear the portfio items tech tag pivot table
        DB::table('portfolio_item_tech_tag_pivot')->truncate();

        /**
         * Seed Fake Items.
         */
        if ($seedFakeItems) {
            // Get the Tags
            $portfolioTags = PortfolioItemTag::pluck('tag')->all();
            $portfolioTechTags = PortfolioItemTechTag::pluck('tag')->all();

            factory(PortfolioItem::class, 100)->create()->each(function ($portfolioItem) use ($portfolioTags, $portfolioTechTags) {
                shuffle($portfolioTags);
                $portfolioItemTags = [$portfolioTags[0]];

                shuffle($portfolioTechTags);
                $portfolioItemTechTags = [$portfolioTechTags[0]];

                // 40% of the time we're assigning portfolioTags, assign 2
                if (mt_rand(1, 100) <= 40) {
                    $portfolioItemTags[] = $portfolioTags[1];
                }

                // 90% of the time we're assigning portfolioTags, assign 4
                if (mt_rand(1, 100) <= 90) {
                    $portfolioItemTechTags[] = $portfolioTechTags[0];
                    $portfolioItemTechTags[] = $portfolioTechTags[1];
                    $portfolioItemTechTags[] = $portfolioTechTags[2];
                    $portfolioItemTechTags[] = $portfolioTechTags[3];
                }

                $portfolioItem->syncTags($portfolioItemTags);
                $portfolioItem->syncTechTags($portfolioItemTechTags);
            });
        }

        /**
         * Seed Real Items.
         */
        if ($seedRealItems) {
            $items = [
                [
                    'slug'                  => 'experienceeverythingkce',
                    'title'                 => 'Kindcare Intranet and LMS',
                    'subtitle'              => 'Kindcare Intranet and Learning Management System',
                    'content_raw'           => 'Kindcare Intranet and Full Learning Management System.',
                    'content_html'          => '<p>Kindcare Intranet and Full Learning Management System.</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/kindercare.png',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/kindercare.png',
                    'project_link_enabled'  => 0,
                    'project_link'          => 'https://experienceeverythingkce.com/',
                    'meta_description'      => 'Kindcare Intranet and Learning Management System',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development'],
                    'tech_tags'             => ['laravel', 'php', 'html_5', 'javascript', 'vue_js', 'sass_scss'],
                ],
                [
                    'slug'                  => 'vernier',
                    'title'                 => 'Vernier Software & Technology',
                    'subtitle'              => 'Education Software & Equipment',
                    'content_raw'           => 'Full website front end rebuild for 4000+ pages with E-commerce section. Build back end templating engine to handle loads with various API inegrations.',
                    'content_html'          => '<p>Full website front end rebuild for 4000+ pages with E-commerce section.</p><p>Build back end templating engine to handle loads with various API inegrations.</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/vernier.png',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/vernier.png',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'https://www.vernier.com/',
                    'meta_description'      => 'Vernier Software & Technology, Education Software & Equipment',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development', 'design'],
                    'tech_tags'             => ['php', 'javscript', 'bootstrap', 'html_5'],
                ],
                [
                    'slug'                  => 'pela',
                    'title'                 => 'Portland English Language Academy',
                    'subtitle'              => 'Complete Build',
                    'content_raw'           => 'Complete front and backend build on WordPress CMS with custom theme and templates.',
                    'content_html'          => '<p>Complete front and backend build on WordPress CMS with custom theme and templates.</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/pela-jeremy.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/pela-jeremy.jpg',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'https://portlandenglish.edu/',
                    'meta_description'      => 'Portland English Language Academy | Complete Build',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development'],
                    'tech_tags'             => ['php', 'wordpress', 'html_5', 'sass_scss'],
                ],
                [
                    'slug'                  => 'gts',
                    'title'                 => 'GTS Servvices',
                    'subtitle'              => 'Application Marketing with Subscription Management',
                    'content_raw'           => 'Application Marketing with Subscription Management.',
                    'content_html'          => '<p>Application Marketing Website with Subscription Management.</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/gts.png',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/gts.png',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'https://gtsservices.com/',
                    'meta_description'      => 'GTS Servvices | Application Marketing with Subscription Management',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development'],
                    'tech_tags'             => ['php', 'wordpress', 'html_5', 'sass_scss', 'chargify', 'api'],
                ],
                [
                    'slug'                  => 'cityhomepdx',
                    'title'                 => 'City Home Portland',
                    'subtitle'              => 'City Home Portland | Furniture and Home Decor',
                    'content_raw'           => 'City Home Portland - Furniture and Home Decor. Theme and template development.',
                    'content_html'          => '<p>City Home Portland - Furniture and Home Decor.</p><p>Theme and template development.</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/jeremy-cityhomepdx-com.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/jeremy-cityhomepdx-com.jpg',
                    'project_link_enabled'  => 0,
                    'project_link'          => 'City Home Portland - Furniture and Home Decor. Theme and template development.',
                    'meta_description'      => 'City Home Portland - Furniture and Home Decor. Theme and template development.',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development'],
                    'tech_tags'             => ['php', 'wordpress', 'html_5'],
                ],
                [
                    'slug'                  => 'cityhomepdx_landing',
                    'title'                 => 'City Home Portland Landing Page',
                    'subtitle'              => 'Landing Page',
                    'content_raw'           => 'City Home Portland - Landing Page',
                    'content_html'          => '<p>City Home Portland - Landing Page</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/cityhomepdx-landing.png',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/cityhomepdx-landing.png',
                    'project_link_enabled'  => 0,
                    'project_link'          => 'null',
                    'meta_description'      => 'City Home Portland - Landing Page',
                    'enabled'               => 1,
                    'tags'                  => ['front_end_development'],
                    'tech_tags'             => ['html_5', 'sass_scss'],
                ],
                [
                    'slug'                  => 'facebook-contest-app',
                    'title'                 => 'Facebook Contest App',
                    'subtitle'              => 'Facebook Application',
                    'content_raw'           => 'Using the Facebook APK to interact with custom database and generate business leads.',
                    'content_html'          => '<p>Using the Facebook APK to interact with custom database and generate business leads.</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone-och-fb-jk.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone-och-fb-jk.jpg',
                    'project_link_enabled'  => 0,
                    'project_link'          => 'null',
                    'meta_description'      => 'Facebook Contest App',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development', 'design'],
                    'tech_tags'             => ['php', 'html_5', 'facebook_sdk'],
                ],
                [
                    'slug'                  => 'facebook-app-probono',
                    'title'                 => 'ProBono | Facebook Wall Feed Plugin for Website',
                    'subtitle'              => 'Facebook Wall Feed Plugin for Website',
                    'content_raw'           => 'Using the Facebook APK to interact with Facebook API to pull wall data for an animal shelter.',
                    'content_html'          => '<p>Using the Facebook APK to interact with Facebook API to pull wall data for an animal shelter.</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone-ruincreek-fb-jk.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone-ruincreek-fb-jk.jpg',
                    'project_link_enabled'  => 0,
                    'project_link'          => 'null',
                    'meta_description'      => 'Facebook Wall Feed Plugin for Website',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development'],
                    'tech_tags'             => ['php', 'facebook_sdk'],
                ],
                [
                    'slug'                  => 'facebook-survey-app',
                    'title'                 => 'Facebook Survey App',
                    'subtitle'              => 'Facebook Application',
                    'content_raw'           => 'Using the Facebook APK to interact with Facebook API for custom survey.',
                    'content_html'          => '<p>Using the Facebook APK to interact with Facebook API for custom survey.</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone-ul-fb-jk.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone-ul-fb-jk.jpg',
                    'project_link_enabled'  => 0,
                    'project_link'          => '',
                    'meta_description'      => 'Facebook Survey Application',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development'],
                    'tech_tags'             => ['php', 'facebook_sdk'],
                ],
                [
                    'slug'                  => 'custom-cms-api-dev',
                    'title'                 => 'Integration Custom CMS and API',
                    'subtitle'              => 'Integration Custom CMS and API | Design by Taggart Media Group',
                    'content_raw'           => 'Integration Custom CMS and API | Design by Taggart Media Group',
                    'content_html'          => '<p>Integration Custom CMS and API | Design by Taggart Media Group</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/trufusion-jeremy.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/trufusion-jeremy.jpg',
                    'project_link_enabled'  => 0,
                    'project_link'          => 'null',
                    'meta_description'      => 'Integration Custom CMS and API | Design by Taggart Media Group',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development'],
                    'tech_tags'             => ['php', 'mindbody_api'],
                ],
                [
                    'slug'                  => 'android-application',
                    'title'                 => 'Oil Can Henrys Android Application',
                    'subtitle'              => 'Android Application',
                    'content_raw'           => 'Oil Can Henrys Android Application',
                    'content_html'          => '<p>Interactive Media In Store Media Application</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/och.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/och.jpg',
                    'project_link_enabled'  => 1,
                    'project_link'          => '',
                    'meta_description'      => 'Oil Can Henrys Android Application',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development', 'design'],
                    'tech_tags'             => ['android', 'java'],
                ],
                [
                    'slug'                  => 'real-time-locator',
                    'title'                 => 'Real Time Locator Using Google Maps API3',
                    'subtitle'              => 'Real Time Locator Using Google Maps API3 for Oil Can Henry\'s',
                    'content_raw'           => 'Real Time Locator Using Google Maps API3 for Oil Can Henry\'s',
                    'content_html'          => '<p>Real Time Locator Using Google Maps API3 for Oil Can Henry\'s</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone-och-locator-jk.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone-och-locator-jk.jpg',
                    'project_link_enabled'  => 1,
                    'project_link'          => '',
                    'meta_description'      => 'Real Time Locator Using Google Maps API3 for Oil Can Henrys',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development', 'design'],
                    'tech_tags'             => ['php', 'google_api'],
                ],
                [
                    'slug'                  => 'marketing-site-cellularoneonline',
                    'title'                 => 'Cellular One Online',
                    'subtitle'              => 'Marketing and E-Commerce Website',
                    'content_raw'           => 'Cellular One Online | Marketing and E-Commerce Website',
                    'content_html'          => '<p>Cellular One Online | Marketing and E-Commerce Website</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/cellularone-jeremy.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/cellularone-jeremy.jpg',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'https://www.cellularoneonline.com/',
                    'meta_description'      => 'Marketing and E-Commerce Website - Cellular One Online',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development'],
                    'tech_tags'             => ['php', 'laravel', 'cms', 'html_5'],
                ],
                [
                    'slug'                  => 'marketing-site-arcada',
                    'title'                 => 'Arcada Management AMO',
                    'subtitle'              => 'Company Marketing Website',
                    'content_raw'           => 'Arcada Management AMO | Company Marketing Website',
                    'content_html'          => '<p>Arcada Management AMO | Company Marketing Website</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone.jpg',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'https://www.arcadiamgmt.com/',
                    'meta_description'      => 'Company Marketing Website - Arcadia',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development'],
                    'tech_tags'             => ['php', 'laravel', 'cms', 'foundation', 'html_5'],
                ],
                [
                    'slug'                  => 'marketing-site-nails',
                    'title'                 => 'Your Nail & Spa',
                    'subtitle'              => 'Company Marketing Website',
                    'content_raw'           => 'Your Nail & Spa | Company Marketing Website',
                    'content_html'          => '<p>Your Nail & Spa | Company Marketing Website</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone-yournailsphoenix.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone-yournailsphoenix.jpg',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'http://www.yournailsphoenix.com/',
                    'meta_description'      => 'Company Marketing Website - Nails',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development', 'design'],
                    'tech_tags'             => ['php', 'google_api', 'cms'],
                ],
                [
                    'slug'                  => 'marketing-site-nails',
                    'title'                 => 'fightthebites.com',
                    'subtitle'              => 'Government Marketing Website',
                    'content_raw'           => 'fightthebites.com | Government Marketing Website',
                    'content_html'          => '<p>fightthebites.com | Government Marketing Website</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/ftb-jeremy.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/ftb-jeremy.jpg',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'http://fightthebites.com/',
                    'meta_description'      => 'Government Marketing Website - fightthebites.com',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development', 'design'],
                    'tech_tags'             => ['php', 'cms'],
                ],
                [
                    'slug'                  => 'small-business-e-commerce',
                    'title'                 => 'Small Business Website | Online Commerce',
                    'subtitle'              => 'Small Business Website | Online Commerce',
                    'content_raw'           => 'Small Business Website | Online Commerce',
                    'content_html'          => '<p>Small Business Website | Online Commerce</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone-bb-jeremy.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone-bb-jeremy.jpg',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'http://www.busybeemanufacturing.com',
                    'meta_description'      => 'Small Business Website | Online Commerce',
                    'enabled'               => 1,
                    'tags'                  => ['front_end_development'],
                    'tech_tags'             => ['html_5', 'sass_scss'],
                ],
                [
                    'slug'                  => 'business-marketing-carsten',
                    'title'                 => 'Institute Marketing Website',
                    'subtitle'              => 'Institute Marketing Website',
                    'content_raw'           => 'Institute Marketing Website',
                    'content_html'          => '<p>Institute Marketing Website</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/carsten-jeremy.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/carsten-jeremy.jpg',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'https://www.carsteninstitute.com/',
                    'meta_description'      => 'Institute Marketing Website',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development'],
                    'tech_tags'             => ['html_5', 'sass_scss', 'php', 'foundation'],
                ],
                [
                    'slug'                  => 'business-marketing-ultherapy',
                    'title'                 => 'Business Marketing Website',
                    'subtitle'              => 'Business Marketing Website',
                    'content_raw'           => 'Business Marketing Website',
                    'content_html'          => '<p>Business Marketing Website</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/ultherapy-jeremy.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/ultherapy-jeremy.jpg',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'https://ultherapy.com/',
                    'meta_description'      => 'Business Marketing Website',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development'],
                    'tech_tags'             => ['html_5', 'sass_scss', 'google_api', 'php'],
                ],
                [
                    'slug'                  => 'daycare',
                    'title'                 => 'ProBono | Small Business Website',
                    'subtitle'              => 'ProBono | Small Business Website',
                    'content_raw'           => 'ProBono | Small Business Website for local Daycare',
                    'content_html'          => '<p>ProBono | Small Business Website for local Daycare</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone-ls-jeremy.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone-ls-jeremy.jpg',
                    'project_link_enabled'  => 0,
                    'project_link'          => '',
                    'meta_description'      => 'ProBono | Small Business Website for local Daycare',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development', 'design'],
                    'tech_tags'             => ['php', 'google_api', 'html_5', 'sass_scss'],
                ],
                [
                    'slug'                  => 'paracore',
                    'title'                 => 'ParaCore Website',
                    'subtitle'              => 'ParaCore Website',
                    'content_raw'           => 'Complete ParaCore Website built in 24 hours strait hackathon style.',
                    'content_html'          => '<p>Complete ParaCore Website built in 24 hours strait hackathon style.</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone-paracore.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone-paracore.jpg',
                    'project_link_enabled'  => 0,
                    'project_link'          => 'https://www.paracore.com/',
                    'meta_description'      => 'ParaCore Website',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development'],
                    'tech_tags'             => ['laravel', 'php', 'html_5', 'javascript', 'sass_scss', 'foundation'],
                ],
                [
                    'slug'                  => 'Enlighten-MD',
                    'title'                 => 'Enlighten MD Website',
                    'subtitle'              => 'Enlighten MD | Medical Website',
                    'content_raw'           => 'Enlighten MD Medical Office Website',
                    'content_html'          => '<p>Enlighten MD Medical Office Website</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone-enlighten.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/combined-desktop-ipad-iphone-enlighten.jpg',
                    'project_link_enabled'  => 0,
                    'project_link'          => '',
                    'meta_description'      => 'Enlighten MD Medical Office Website',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development'],
                    'tech_tags'             => ['laravel', 'php', 'html_5', 'sass_scss', 'foundation'],
                ],
                [
                    'slug'                  => 'laravel-auth',
                    'title'                 => 'Laravel Auth',
                    'subtitle'              => 'Laravel 7 with user authentication, registration with email confirmation, social media authentication, password recovery, and captcha protection.',
                    'content_raw'           => 'Laravel 7 with user authentication, registration with email confirmation, social media authentication, password recovery, and captcha protection. Uses offical [Bootstrap 4](http://getbootstrap.com). This also makes full use of Controllers for the routes, templates for the views, and makes use of middleware for routing. Project can be stood up in minutes.',
                    'content_html'          => '<p>Laravel 7 with user authentication, registration with email confirmation, social media authentication, password recovery, and captcha protection. Uses offical [Bootstrap 4](http://getbootstrap.com).</p><p>This also makes full use of Controllers for the routes, templates for the views, and makes use of middleware for routing. </p><p>Complete Build of Laravel 5.8 with Email Registration Verification, Social Authentication, User Roles and Permissions, User Profiles, and Admin restricted user management system. Built on Bootstrap 4.</p><p>Project can be stood up in minutes.</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/laravel-auth.jpeg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/laravel-auth.jpeg',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'https://github.com/jeremykenedy/laravel-auth',
                    'meta_description'      => 'Laravel 5.8 with user authentication, registration with email confirmation, social media authentication, password recovery, and captcha protection. ',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development', 'design', 'opensource'],
                    'tech_tags'             => ['laravel', 'php', 'bootstrap', 'html_5', 'opensource'],
                ],
                [
                    'slug'                  => 'laravel-roles',
                    'title'                 => 'Laravel Roles',
                    'subtitle'              => 'A Powerful open source package for handling roles and permissions in Laravel. Supports Laravel 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 6.0, and 7.0.',
                    'content_raw'           => 'A Powerful open source package for handling roles and permissions in Laravel. Supports Laravel 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 6.0, and 7.0',
                    'content_html'          => '<p>A Powerful open source package for handling roles and permissions in Laravel. Supports Laravel 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 6.0, and 7.0</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/github-project-images/laravel-roles/screenshots/roles-gui-1.png',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/github-project-images/laravel-roles/screenshots/roles-gui-1.png',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'https://github.com/jeremykenedy/laravel-roles',
                    'meta_description'      => 'A Powerful open source package for handling roles and permissions in Laravel. Supports Laravel 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 6.0, and 7.0 ',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development', 'design', 'opensource'],
                    'tech_tags'             => ['laravel', 'php', 'bootstrap', 'html_5', 'opensource'],
                ],
                [
                    'slug'                  => 'laravel-users',
                    'title'                 => 'Laravel Users',
                    'subtitle'              => 'An Open Source Users Management Package for Laravel',
                    'content_raw'           => 'A Users Management Package that includes all necessary routes, views, models, and controllers for a user management dashboard and associated pages for managing Laravels built in user scaffolding. Built for Laravel 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 6.0. and 7.0.',
                    'content_html'          => '<p>A Powerful open source package for handling roles and permissions in Laravel. Supports Laravel 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 6.0, and 7.0</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/github-project-images/laravel-users/show-users.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/github-project-images/laravel-users/show-users.jpg',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'https://github.com/jeremykenedy/laravel-users',
                    'meta_description'      => 'An Open Source Users Management Package for Laravel',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development', 'design', 'opensource'],
                    'tech_tags'             => ['laravel', 'php', 'bootstrap', 'html_5', 'opensource'],
                ],
                [
                    'slug'                  => 'laravel-logger',
                    'title'                 => 'Laravel Logger',
                    'subtitle'              => 'An open source out the box activity logger for your Laravel or Lumen application.',
                    'content_raw'           => 'An out the box activity logger for your Laravel or Lumen application. Laravel logger is an activity event logger for your laravel application. It comes out the box with ready to use with dashboard to view your activity. Laravel logger can be added as a middleware or called through a trait. This package is easily configurable and customizable. Supports Laravel 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 6, and 7+',
                    'content_html'          => '<p>An out the box activity logger for your Laravel or Lumen application. Laravel logger is an activity event logger for your laravel application. It comes out the box with ready to use with dashboard to view your activity. Laravel logger can be added as a middleware or called through a trait. This package is easily configurable and customizable. Supports Laravel 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 6, and 7+</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/github-project-images/laravel-logger/1-dashboard.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/github-project-images/laravel-logger/1-dashboard.jpg',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'https://github.com/jeremykenedy/laravel-logger',
                    'meta_description'      => 'An open source out the box activity logger for your Laravel or Lumen application.',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development', 'design', 'opensource'],
                    'tech_tags'             => ['laravel', 'php', 'bootstrap', 'html_5', 'opensource'],
                ],
                [
                    'slug'                  => 'laravel2step',
                    'title'                 => 'Laravel 2-Step Verification',
                    'subtitle'              => 'Laravel 2-Step verification is a package to add 2-Step user authentication to any Laravel project easily. ',
                    'content_raw'           => 'Laravel 2-Step verification is a package to add 2-Step user authentication to any Laravel project easily. It is configurable and customizable. It uses notifications to send the user an email with a 4-digit verification code.  Laravel 2-Step Authentication Verification for Laravel. Can be used in out the box with Laravel\'s authentication scaffolding or integrated into other projects.',
                    'content_html'          => '<p>Laravel 2-Step verification is a package to add 2-Step user authentication to any Laravel project easily. It is configurable and customizable. It uses notifications to send the user an email with a 4-digit verification code.  Laravel 2-Step Authentication Verification for Laravel. Can be used in out the box with Laravel\'s authentication scaffolding or integrated into other projects.</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/github-project-images/laravel2step/1-verification-page.jpeg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/github-project-images/laravel2step/1-verification-page.jpeg',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'https://github.com/jeremykenedy/laravel2step',
                    'meta_description'      => 'Laravel 2-Step verification is a package to add 2-Step user authentication to any Laravel project easily. ',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development', 'design', 'opensource'],
                    'tech_tags'             => ['laravel', 'php', 'bootstrap', 'html_5', 'opensource'],
                ],
                [
                    'slug'                  => 'laravel-blocker',
                    'title'                 => 'Laravel Blocker',
                    'subtitle'              => 'Larave Blocker is a middleware interface to block users, emails, ip addresses, domain names, cities, states, countries, continents, and regions from using Laravel applications, ',
                    'content_raw'           => 'Larave Blocker is a middleware interface to block users, emails, ip addresses, domain names, cities, states, countries, continents, and regions from using your application, logging in, or registering. The types of items to be blocked can be extended to what you think via a seed. The items you are blocking have a CRUD interface along with a softdeletes interface.',
                    'content_html'          => '<p>Larave Blocker is a middleware interface to block users, emails, ip addresses, domain names, cities, states, countries, continents, and regions from using your application, logging in, or registering. The types of items to be blocked can be extended to what you think via a seed. The items you are blocking have a CRUD interface along with a softdeletes interface.</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/github-project-images/laravel-blocker/blocker0.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/github-project-images/laravel-blocker/blocker0.jpg',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'https://github.com/jeremykenedy/laravel-blocker',
                    'meta_description'      => 'Larave Blocker is a middleware interface to block users, emails, ip addresses, domain names, cities, states, countries, continents, and regions from using Laravel applications, ',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development', 'design', 'opensource'],
                    'tech_tags'             => ['laravel', 'php', 'bootstrap', 'html_5', 'opensource'],
                ],
                [
                    'slug'                  => 'laravel-phpinfo',
                    'title'                 => 'Laravel Exception Notifier',
                    'subtitle'              => 'Laravel PHP Info is a package that provides a PHPInfo() page using blade templating. ',
                    'content_raw'           => 'Laravel PHP Info is a package that provides a PHPInfo() page using blade templating.  The config file can be used to enable/disable auth protection and specify the roles middleware.',
                    'content_html'          => '<p>Laravel PHP Info is a package that provides a PHPInfo() page using blade templating.  The config file can be used to enable/disable auth protection and specify the roles middleware.</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/github-project-images/laravel-phpinfo/phpinfo1.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/github-project-images/laravel-phpinfo/phpinfo1.jpg',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'https://github.com/jeremykenedy/laravel-phpinfo',
                    'meta_description'      => 'Laravel PHP Info is a package that provides a PHPInfo() page using blade templating. ',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development', 'design', 'opensource'],
                    'tech_tags'             => ['laravel', 'php', 'bootstrap', 'html_5', 'opensource'],
                ],
                [
                    'slug'                  => 'laravel-https',
                    'title'                 => 'Laravel HTTPS Web and API Checker',
                    'subtitle'              => 'Laravel Https is middleware to check for Secure HTTP requests. ',
                    'content_raw'           => 'Laravel Https is middleware to check for Secure HTTP requests. Laravel Https has can check for HTTPS and throw an error or automatically redirect to HTTPS.',
                    'content_html'          => '<p>Laravel Https is middleware to check for Secure HTTP requests. Laravel Https has can check for HTTPS and throw an error or automatically redirect to HTTPS.</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/github-project-images/laravel-https/1-http-call.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/github-project-images/laravel-https/1-http-call.jpg',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'https://github.com/jeremykenedy/laravel-https',
                    'meta_description'      => 'Laravel Https is middleware to check for Secure HTTP requests. ',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development', 'design', 'opensource'],
                    'tech_tags'             => ['laravel', 'php', 'bootstrap', 'html_5', 'opensource'],
                ],
                [
                    'slug'                  => 'laravel-exception-notifier',
                    'title'                 => 'Laravel Exception Notifier',
                    'subtitle'              => 'Laravel Exception Notifier will send an email of the error along with the stack trace to the chosen recipients. ',
                    'content_raw'           => 'Laravel Exception Notifier will send an email of the error along with the stack trace to the chosen recipients. This Package includes all necessary traits, views, configs, and Mailers for email notifications upon your applications exceptions. You can customize who send to, cc to, bcc to, enable/disable, and custom subject or default subject based on environment. Built for Laravel 5.2, 5.3, 5.4, 5.5+.  Get the errors and fix them before the client even reports them, that\'s why this exists! For Laravel 5, 6, and 7.',
                    'content_html'          => '<p>Laravel Exception Notifier will send an email of the error along with the stack trace to the chosen recipients. This Package includes all necessary traits, views, configs, and Mailers for email notifications upon your applications exceptions. You can customize who send to, cc to, bcc to, enable/disable, and custom subject or default subject based on environment. Built for Laravel 5.2, 5.3, 5.4, 5.5+.  Get the errors and fix them before the client even reports them, that\'s why this exists! For Laravel 5, 6, and 7.</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/github-project-images/laravel-exception-notifier/exception-error-email-min.jpeg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/github-project-images/laravel-exception-notifier/exception-error-email-min.jpeg',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'https://github.com/jeremykenedy/laravel-exception-notifier',
                    'meta_description'      => 'Laravel Exception Notifier will send an email of the error along with the stack trace to the chosen recipients. ',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development', 'design', 'opensource'],
                    'tech_tags'             => ['laravel', 'php', 'bootstrap', 'html_5', 'opensource'],
                ],
                [
                    'slug'                  => 'larablog',
                    'title'                 => 'LaraBlog',
                    'subtitle'              => 'An open source Laravel Soundboard with Admin Panel CRUD (Create Read Update Delete) built on Laravel, Bootstrap, and Vue.js',
                    'content_raw'           => 'An open source Laravel Soundboard with Admin Panel CRUD (Create Read Update Delete) built on Laravel, Bootstrap, and Vue.js',
                    'content_html'          => '<p>An open source Laravel Soundboard with Admin Panel CRUD (Create Read Update Delete) built on Laravel, Bootstrap, and Vue.js</p>',
                    'item_image'            => 'https://github-project-images.s3-us-west-2.amazonaws.com/laravel-soundboard/1-home.jpg',
                    'item_image_large'      => 'https://github-project-images.s3-us-west-2.amazonaws.com/laravel-soundboard/1-home.jpg',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'https://github.com/jeremykenedy/laravel-soundboard',
                    'meta_description'      => 'An open source Laravel Soundboard with Admin Panel CRUD built on Laravel, Bootstrap, and Vue.js',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development', 'design', 'opensource'],
                    'tech_tags'             => ['laravel', 'php', 'bootstrap', 'html_5', 'opensource'],
                ],
                [
                    'slug'                  => 'larablog',
                    'title'                 => 'LaraBlog',
                    'subtitle'              => 'A powerful open source Laravel Blog.',
                    'content_raw'           => 'A powerful open source Laravel Blog with WYSWYG and CRUD (Create Read Update Delete) built on Laravel 5.8 and Bootstrap 4. Larablog is licensed under the MIT license.',
                    'content_html'          => '<p>A powerful open source Laravel Blog with WYSWYG and CRUD (Create Read Update Delete) built on Laravel 5.8 and Bootstrap 4</p><p>Larablog is licensed under the MIT license.</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/larablog.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/jeremykenedy.com/images/portfolio-images/larablog.jpg',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'https://github.com/jeremykenedy/larablog',
                    'meta_description'      => 'larablog',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development', 'design', 'opensource'],
                    'tech_tags'             => ['laravel', 'php', 'bootstrap', 'html_5', 'opensource'],
                ],
                [
                    'slug'                  => 'laravel-material-design',
                    'title'                 => 'Laravel Material Design',
                    'subtitle'              => 'Laravel 5.6 on Material Design Lite 1.3 with user authentication, registration with email confirmation, and social media authentication. ',
                    'content_raw'           => 'Laravel 5.6 on Material Design Lite 1.3 with user authentication, registration with email confirmation, social media authentication, password recovery, and captcha protection. This makes full use of Controllers for the routes, templates for the views, and makes use of middleware for routing. Uses laravel ORM modeling and has CRUD (Create Read Update Delete) functionality for all tasks. Quick setup, can be done in 5 minutes. It will take longer to obtain your Facebook, Twitter, and Google Plus API Keys than it will to set this up.',
                    'content_html'          => '<p>Laravel 5.6 on Material Design Lite 1.3 with user authentication, registration with email confirmation, social media authentication, password recovery, and captcha protection. This makes full use of Controllers for the routes, templates for the views, and makes use of middleware for routing. Uses laravel ORM modeling and has CRUD (Create Read Update Delete) functionality for all tasks. Quick setup, can be done in 5 minutes. It will take longer to obtain your Facebook, Twitter, and Google Plus API Keys than it will to set this up.</p>',
                    'item_image'            => 'https://s3-us-west-2.amazonaws.com/laravel-material-design/screenshots/user-list-desktop.jpg',
                    'item_image_large'      => 'https://s3-us-west-2.amazonaws.com/laravel-material-design/screenshots/user-list-desktop.jpg',
                    'project_link_enabled'  => 1,
                    'project_link'          => 'https://github.com/jeremykenedy/laravel-material-design',
                    'meta_description'      => 'Laravel 5.6 on Material Design Lite 1.3 with user authentication, registration with email confirmation, and social media authentication. ',
                    'enabled'               => 1,
                    'tags'                  => ['back_end_development', 'front_end_development', 'design', 'opensource'],
                    'tech_tags'             => ['laravel', 'php', 'bootstrap', 'html_5', 'opensource'],
                ],

                // [
                //     'slug'                  => null,
                //     'title'                 => null,
                //     'subtitle'              => null,
                //     'content_raw'           => null,
                //     'content_html'          => null,
                //     'item_image'            => null,
                //     'item_image_large'      => null,
                //     'project_link_enabled'  => 1,
                //     'project_link'          => null,
                //     'meta_description'      => null,
                //     'enabled'               => 1,
                //     'tags'                  => [],
                //     'tech_tags'             => [],
                // ],
            ];

            $sortOrder = 0;
            foreach ($items as $item) {
                $newPortfolioItem = PortfolioItem::where('slug', '=', $item['slug'])->first();
                if ($newPortfolioItem === null) {
                    $newPortfolioItem = PortfolioItem::create([
                        'slug'                  => $item['slug'],
                        'title'                 => $item['title'],
                        'subtitle'              => $item['subtitle'],
                        'content_raw'           => $item['content_raw'],
                        'content_html'          => $item['content_html'],
                        'item_image'            => $item['item_image'],
                        'item_image_large'      => $item['item_image_large'],
                        'project_link_enabled'  => $item['project_link_enabled'],
                        'project_link'          => $item['project_link'],
                        'meta_description'      => $item['meta_description'],
                        'enabled'               => $item['enabled'],
                        'sort_order'            => $sortOrder,
                    ]);
                    $newPortfolioItem->syncTags($item['tags']);
                    $newPortfolioItem->syncTechTags($item['tech_tags']);
                    $sortOrder = $sortOrder + 1;
                }
            }
        }
    }
}
